# Logistic Regression

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_excel('Data.xlsx')
df = df.fillna(0)
X = df.iloc[:, [0]].values
y = df.iloc[:, 5].values

In [3]:
print(X,',',y)

[['France']
 ['Spain']
 ['Germany']
 ['Spain']
 ['Germany']
 ['France']
 ['Spain']
 ['France']
 ['Germany']
 ['France']] , [72000. 48000. 54000. 61000.     0. 58000. 52000. 79000. 83000. 67000.]


### One-Hot Encode

In [4]:
labelencoder = LabelEncoder()
X[: , 0] = labelencoder.fit_transform(X[ : , 0])
onehotencoder = OneHotEncoder(categories='auto')
X = onehotencoder.fit_transform(X).toarray()

In [5]:
X

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
X_train, X_test, y_train, y_test

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.]]),
 array([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]]),
 array([67000., 48000., 52000., 79000., 61000., 72000., 58000.]),
 array([54000., 83000.,     0.]))

### Scaling Data By Taking Z-scores

In [8]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Implementing classifier

In [9]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
y_pred = classifier.predict(X_test)

In [11]:
y_pred

array([61000., 61000., 61000.])