# Multiple Linear Regression

## 1. Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_excel('Data.xlsx')

In [3]:
df = df.fillna(0)
X = df.iloc[ : , :-1].values
Y = df.iloc[ : ,  2 ].values

In [4]:
X

array([['France', 44.0, 72000.0, 'No', 'M'],
       ['Spain', 27.0, 48000.0, 'Yes', 'M'],
       ['Germany', 30.0, 54000.0, 'No', 'F'],
       ['Spain', 38.0, 61000.0, 'No', 'M'],
       ['Germany', 40.0, 0.0, 'Yes', 'F'],
       ['France', 35.0, 58000.0, 'Yes', 'F'],
       ['Spain', 0.0, 52000.0, 'No', 'F'],
       ['France', 48.0, 79000.0, 'Yes', 'M'],
       ['Germany', 50.0, 83000.0, 'No', 'M'],
       ['France', 37.0, 67000.0, 'Yes', 'M']], dtype=object)

In [5]:
Y

array([72000., 48000., 54000., 61000.,     0., 58000., 52000., 79000.,
       83000., 67000.])

## 2. One-Hot-Encode

In [6]:
labelencoder = LabelEncoder()
X[: , 0] = labelencoder.fit_transform(X[ : , 0])
onehotencoder = OneHotEncoder(categories='auto')
X = onehotencoder.fit_transform(X).toarray()

## 3. Predict

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [8]:
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
y_pred = regressor.predict(X_test)

In [10]:
X_test

array([[0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.]])

In [11]:
y_pred

array([43199.93504398, 54584.5381164 ])