In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3.0])
a

array([1., 2., 3.])

#### Shape Of array

In [3]:
a.shape

(3,)

In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)
print("shape :" ,b.shape)

[[1 2 3 4]
 [5 6 7 8]]
shape : (2, 4)


#### type Of array

In [5]:
b.dtype

dtype('int32')

In [6]:
b.sum(1)

array([10, 26])

#### Functions On array

In [10]:
# add 1 to every element
print ("Adding 1 to every element:", a+1)
 
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
 
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
 
# square each element
print ("Squaring each element:", a**2)
 
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
 
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
 
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [[ 2  3  4]
 [ 4  5  6]
 [10  7  1]]
Subtracting 3 from each element: [[-2 -1  0]
 [ 0  1  2]
 [ 6  3 -3]]
Multiplying each element by 10: [[10 20 30]
 [30 40 50]
 [90 60  0]]
Squaring each element: [[ 1  4  9]
 [ 9 16 25]
 [81 36  0]]
Doubled each element of original array: [[ 2  4  6]
 [ 6  8 10]
 [18 12  0]]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


#### Complex Numbers On Array

In [12]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)

[1.+0.j 2.+0.j 3.+0.j]


#### Slicing

In [17]:
a = np.arange(10) 
s = slice(2,9,2) 
print('a :', a)
print('s :', s)
print('a[s] :' ,a[s])

a : [0 1 2 3 4 5 6 7 8 9]
s : slice(2, 9, 2)
a[s] : [2 4 6 8]


In [19]:
print('From 2nd index till end :' ,a[2:])

From 2nd element till end : [2 3 4 5 6 7 8 9]


In [21]:
print('From 2nd index before fifth index :' ,a[2:5])

From 2nd index before fifth index : [2 3 4]


In [30]:
twoD_array = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [31]:
print(twoD_array)
# twoD_array[start_rows : end_row , start_columns : end_column]
print('The items column 1 onwards are :', twoD_array[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The items column 1 onwards are : [[2 3]
 [5 6]
 [8 9]]


#### axis = 0 is column and axis = 1 is row

In [32]:
print(np.percentile(twoD_array,50))
print(np.percentile(twoD_array,75))
print(np.percentile(twoD_array, 50, axis = 1))
print(np.percentile(twoD_array, 50, axis = 0))

5.0
7.0
[2. 5. 8.]
[4. 5. 6.]


In [36]:
print('Mean:', np.mean(a))
print('Mean:', np.mean(a, axis = 0))

Mean: 4.5
Mean: 4.5


In [37]:
np.std([1,2,3,4])

1.118033988749895

In [38]:
np.var([1,2,3,4])

1.25