In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_excel('Data.xlsx')

In [3]:
df = df.fillna(0)

In [4]:
df.Age = df.Age.astype(float).astype(int)
df.Salary = df.Salary.astype(float).astype(int)

In [5]:
X = df.iloc[:, [1,2]].values
y = df.iloc[:, [3]].values

In [6]:
df

Country  Age  Salary Purchased Gender  EstimatedSalary
0   France   44   72000        No      M          72000.0
1    Spain   27   48000       Yes      M          48000.0
2  Germany   30   54000        No      F          54000.0
3    Spain   38   61000        No      M          61000.0
4  Germany   40       0       Yes      F              0.0
5   France   35   58000       Yes      F          58000.0
6    Spain    0   52000        No      F          52000.0
7   France   48   79000       Yes      M          79000.0
8  Germany   50   83000        No      M          83000.0
9   France   37   67000       Yes      M          67000.0

In [7]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [8]:
X

array([[   44, 72000],
       [   27, 48000],
       [   30, 54000],
       [   38, 61000],
       [   40,     0],
       [   35, 58000],
       [    0, 52000],
       [   48, 79000],
       [   50, 83000],
       [   37, 67000]])

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [10]:
print(X_train,',',X_test,',', y_train,',', y_test)

[[   37 67000]
 [   27 48000]
 [    0 52000]
 [   48 79000]
 [   38 61000]
 [   44 72000]
 [   35 58000]] , [[   30 54000]
 [   50 83000]
 [   40     0]] , [['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']] , [['No']
 ['No']
 ['Yes']]


In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\zawar.LAPTOP-L2O17FMQ\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [13]:
y_pred = classifier.predict(X_test)
y_pred

array(['Yes', 'Yes', 'No'], dtype=object)

In [14]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 2],
       [1, 0]], dtype=int64)