# SVM

In [136]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from matplotlib.colors import ListedColormap
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [162]:
df = pd.read_excel('Data.xlsx')
df = df.fillna(0)
X = df.iloc[:, [0]].values
y = df.iloc[:, [4]].values

In [163]:
X

array([['France'],
       ['Spain'],
       ['Germany'],
       ['Spain'],
       ['Germany'],
       ['France'],
       ['Spain'],
       ['France'],
       ['Germany'],
       ['France']], dtype=object)

In [164]:
y

array([['M'],
       ['M'],
       ['F'],
       ['M'],
       ['F'],
       ['F'],
       ['F'],
       ['M'],
       ['M'],
       ['M']], dtype=object)

### One-Hot Encode

In [165]:
labelencoder = LabelEncoder()
X[: , 0] = labelencoder.fit_transform(X[ : , 0])
onehotencoder = OneHotEncoder(categories='auto')
X = onehotencoder.fit_transform(X).toarray()

In [166]:
labelencoder = LabelEncoder()
y[: , 0] = labelencoder.fit_transform(y[ : , 0])
onehotencoder = OneHotEncoder(categories='auto')
y = onehotencoder.fit_transform(y).toarray()

In [167]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [168]:
X_train

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [169]:
X_test

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [170]:
y_train

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [171]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.]])

### Scaling Data By Taking Z-scores

In [177]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [183]:
X_train = X_train[:,0]

In [184]:
X_test

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Fitting SVM

In [185]:
classifier = SVC(kernel = 'poly', random_state = 0)
classifier.fit(X_train, y_train)

ValueError: Expected 2D array, got 1D array instead:
array=[ 0.8660254  -1.15470054 -1.15470054  0.8660254  -1.15470054  0.8660254
  0.8660254 ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [100]:
y_pred = classifier.predict(X_test)

In [101]:
y_pred

array(['M', 'M', 'M'], dtype=object)